services:
  backend1:
    build:
      context: ./backend
    container_name: backend1
    ports:
      - "5001:5000"
    networks:
      - backend
    depends_on:
      - mysql

  backend2:
    build:
      context: ./backend
    container_name: backend2
    ports:
      - "5002:5000"
    networks:
      - backend
    depends_on:
      - mysql

  backend3:
    build:
      context: ./backend
    container_name: backend3
    ports:
      - "5003:5000"
    networks:
      - backend
    depends_on:
      - mysql

  load-balancer:
    build:
      context: ./haproxy
    container_name: load-balancer
    ports:
      - "8080:80"
      - "8404:8404"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend

  client:
    build:
      context: ./client
    container_name: client
    networks:
      - backend
    depends_on:
      - load-balancer
    logging:
      driver: "syslog"

  mysql:
    build:
      context: ./backend
      dockerfile: Dockerfile-mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_app
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: bank_password
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
     - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - backend

networks:
  backend:
    driver: bridge
